/*
===========================================================
 TradeMind Pro
 V24.0 — INDEPENDENT EDGE-HEALTH CONFIRMATION AUDIT
 ----------------------------------------------------------
 MODE:
 PAPER ONLY
 NO REAL ORDERS

 PURPOSE
 ----------------------------------------------------------
 V23.0 found a promising relationship:

   HEALTHY  -> stronger forward persistence
   DECAYING -> weak / near-flat persistence
   BROKEN   -> unexpectedly positive, but very small sample

 V23.0 used overlapping rolling checkpoints.

 V24.0 is the next scientific step:

   CONFIRM THE V23 EDGE-HEALTH RELATIONSHIP ON A
   SEPARATE, NON-OVERLAPPING CHRONOLOGICAL SLICE.

 IMPORTANT:
 ----------------------------------------------------------
 V24.0 IS DIAGNOSTIC ONLY.

 It does NOT:
   - change candidate discovery
   - change qualification
   - change validation
   - change diversification
   - change true OOS
   - change exits
   - change risk
   - create a trading filter
   - promote HEALTHY
   - suppress DECAYING
   - suppress BROKEN
   - optimize thresholds from confirmation outcomes
   - place live orders

 V22.8/V22.9 HEALTH DEFINITIONS ARE FROZEN:

 HEALTHY:
   prior EV > 0
   AND internal EV change >= -0.10R
   AND late-half EV > 0

 STABLE:
   prior EV > 0
   AND internal EV change >= -0.10R
   AND late-half EV <= 0

 DECAYING:
   prior EV > 0
   AND internal EV change < -0.10R
   AND late-half EV > 0

 BROKEN:
   prior EV > 0
   AND internal EV change < -0.10R
   AND late-half EV <= 0

 NO V24 THRESHOLD IS SELECTED FROM V23 OUTCOMES.
===========================================================
*/

/*
EXPECTED INPUT

confirmationRecords:
    Learning records generated by the EXISTING TradeMind
    strategy mechanics from a separate historical slice.

Each record should contain at minimum:

{
    index,
    side: "SELL",
    resultR,
    setup,
    trend,
    regime,
    volatility,
    timeBucket,
    vwapDirection,
    rsiBucket
}

The confirmation slice MUST NOT overlap the V23
diagnostic slice.

For a genuine independent test, the caller should pass
a separately fetched historical period.

===========================================================
*/

function buildV240IndependentEdgeHealthConfirmation({
    confirmationRecords,
    sourceLabel = "SEPARATE_HISTORICAL_SLICE",
    sourceStartTs = null,
    sourceEndTs = null
}) {

    const VERSION = "V24.0";

    const PRIOR_RECORDS = 40;
    const FORWARD_RECORDS = 20;

    /*
     * These are FROZEN from V22.8/V22.9.
     * They are not fitted by V24.
     */
    const HEALTH_DECAY_THRESHOLD = -0.10;

    const MIN_FORWARD_TRADES = 1;

    const MIN_STATE_OBSERVATIONS = 10;

    function safeArray(value) {
        return Array.isArray(value) ? value : [];
    }

    function num(value, fallback = null) {
        const x = Number(value);
        return Number.isFinite(x) ? x : fallback;
    }

    function round(value, digits = 4) {
        return Number.isFinite(value)
            ? Number(value.toFixed(digits))
            : null;
    }

    function metrics(rows) {

        const data =
            safeArray(rows)
                .filter(
                    x =>
                        Number.isFinite(
                            Number(x.resultR)
                        )
                );

        if (!data.length) {
            return {
                trades: 0,
                wins: 0,
                losses: 0,
                timeouts: 0,
                decisiveTrades: 0,
                winRate: 0,
                netR: 0,
                EV: 0,
                profitFactor: 0
            };
        }

        const wins =
            data.filter(
                x => Number(x.resultR) > 0
            ).length;

        const losses =
            data.filter(
                x => Number(x.resultR) < 0
            ).length;

        const timeouts =
            data.filter(
                x =>
                    String(
                        x.exitReason ??
                        x.exit ??
                        ""
                    )
                        .toUpperCase()
                        .includes("TIMEOUT")
            ).length;

        const decisiveTrades =
            data.filter(
                x =>
                    Number(x.resultR) !== 0
            ).length;

        const netR =
            data.reduce(
                (sum, x) =>
                    sum + Number(x.resultR),
                0
            );

        const totalWinR =
            data
                .filter(
                    x => Number(x.resultR) > 0
                )
                .reduce(
                    (sum, x) =>
                        sum + Number(x.resultR),
                    0
                );

        const totalLossR =
            Math.abs(
                data
                    .filter(
                        x =>
                            Number(x.resultR) < 0
                    )
                    .reduce(
                        (sum, x) =>
                            sum + Number(x.resultR),
                        0
                    )
            );

        return {
            trades: data.length,
            wins,
            losses,
            timeouts,
            decisiveTrades,
            winRate:
                decisiveTrades > 0
                    ? round(
                        wins /
                        decisiveTrades *
                        100,
                        2
                    )
                    : 0,
            netR:
                round(netR),
            EV:
                round(
                    netR /
                    data.length
                ),
            profitFactor:
                totalLossR > 0
                    ? round(
                        totalWinR /
                        totalLossR
                    )
                    : totalWinR > 0
                        ? 999
                        : 0
        };
    }

    function internalEV(rows) {

        const data =
            safeArray(rows)
                .filter(
                    x =>
                        Number.isFinite(
                            Number(x.resultR)
                        )
                );

        if (!data.length) {
            return 0;
        }

        return (
            data.reduce(
                (sum, x) =>
                    sum + Number(x.resultR),
                0
            ) /
            data.length
        );
    }

    function healthState(priorRows) {

        const rows =
            safeArray(priorRows);

        if (
            rows.length <
            PRIOR_RECORDS
        ) {
            return "INSUFFICIENT_HISTORY";
        }

        const priorEV =
            internalEV(rows);

        if (priorEV <= 0) {
            return "NO_POSITIVE_PRIOR_EDGE";
        }

        const midpoint =
            Math.floor(
                rows.length / 2
            );

        const early =
            rows.slice(
                0,
                midpoint
            );

        const late =
            rows.slice(
                midpoint
            );

        const earlyEV =
            internalEV(early);

        const lateEV =
            internalEV(late);

        const internalEVChange =
            lateEV - earlyEV;

        if (
            internalEVChange >=
                HEALTH_DECAY_THRESHOLD &&
            lateEV > 0
        ) {
            return "HEALTHY";
        }

        if (
            internalEVChange >=
                HEALTH_DECAY_THRESHOLD &&
            lateEV <= 0
        ) {
            return "STABLE";
        }

        if (
            internalEVChange <
                HEALTH_DECAY_THRESHOLD &&
            lateEV > 0
        ) {
            return "DECAYING";
        }

        return "BROKEN";
    }

    function contextKey(row) {

        return [
            row.setup ?? "UNKNOWN",
            row.trend ?? "UNKNOWN",
            row.regime ?? "UNKNOWN",
            row.volatility ?? "UNKNOWN",
            row.timeBucket ?? "UNKNOWN",
            row.vwapDirection ?? "UNKNOWN",
            row.rsiBucket ?? "UNKNOWN"
        ].join("|");
    }

    function maxLossStreak(rows) {

        let current = 0;
        let maximum = 0;

        for (const row of safeArray(rows)) {

            const r =
                Number(row.resultR);

            if (r < 0) {
                current++;
                maximum =
                    Math.max(
                        maximum,
                        current
                    );
            } else {
                current = 0;
            }
        }

        return maximum;
    }

    const records =
        safeArray(confirmationRecords)
            .filter(
                x =>
                    x &&
                    x.side === "SELL" &&
                    Number.isFinite(
                        Number(x.index)
                    ) &&
                    Number.isFinite(
                        Number(x.resultR)
                    )
            )
            .sort(
                (a, b) =>
                    Number(a.index) -
                    Number(b.index)
            );

    /*
    ---------------------------------------------------------
    NON-OVERLAPPING CONFIRMATION DESIGN
    ---------------------------------------------------------

    We deliberately DO NOT use rolling checkpoints.

    Confirmation blocks are disjoint.

    Each block:

        40 completed prior SELL records
                   +
        20 immediately following SELL records

    The forward records of one block are never reused as
    the forward records of another block.

    This makes the V24 observations independent at the
    block level, unlike V23's overlapping rolling audit.
    ---------------------------------------------------------
    */

    const transitions = [];

    let cursor = 0;
    let block = 1;

    while (
        cursor +
        PRIOR_RECORDS +
        FORWARD_RECORDS
        <=
        records.length
    ) {

        const prior =
            records.slice(
                cursor,
                cursor +
                PRIOR_RECORDS
            );

        const forward =
            records.slice(
                cursor +
                PRIOR_RECORDS,
                cursor +
                PRIOR_RECORDS +
                FORWARD_RECORDS
            );

        const state =
            healthState(prior);

        if (
            state === "INSUFFICIENT_HISTORY" ||
            state === "NO_POSITIVE_PRIOR_EDGE"
        ) {
            cursor +=
                PRIOR_RECORDS +
                FORWARD_RECORDS;

            block++;
            continue;
        }

        const priorEV =
            internalEV(prior);

        const midpoint =
            Math.floor(
                prior.length / 2
            );

        const earlyEV =
            internalEV(
                prior.slice(
                    0,
                    midpoint
                )
            );

        const lateEV =
            internalEV(
                prior.slice(
                    midpoint
                )
            );

        const forwardMetrics =
            metrics(forward);

        const forwardSuccess =
            forward.length >= MIN_FORWARD_TRADES &&
            forwardMetrics.EV > 0;

        transitions.push({

            block,

            healthState:
                state,

            contextKey:
                contextKey(
                    prior[prior.length - 1]
                ),

            prior: {

                samples:
                    prior.length,

                decisiveTrades:
                    metrics(prior)
                        .decisiveTrades,

                EV:
                    round(priorEV),

                PF:
                    metrics(prior)
                        .profitFactor,

                winRate:
                    metrics(prior)
                        .winRate,

                internalEarlyEV:
                    round(earlyEV),

                internalLateEV:
                    round(lateEV),

                internalEVChange:
                    round(
                        lateEV -
                        earlyEV
                    ),

                maxLossStreak:
                    maxLossStreak(prior),

                firstRecordIndex:
                    prior[0]?.index ??
                    null,

                lastRecordIndex:
                    prior[
                        prior.length - 1
                    ]?.index ??
                    null
            },

            forward: {

                trades:
                    forwardMetrics.trades,

                decisiveTrades:
                    forwardMetrics.decisiveTrades,

                wins:
                    forwardMetrics.wins,

                losses:
                    forwardMetrics.losses,

                timeouts:
                    forwardMetrics.timeouts,

                winRate:
                    forwardMetrics.winRate,

                netR:
                    forwardMetrics.netR,

                EV:
                    forwardMetrics.EV,

                PF:
                    forwardMetrics.profitFactor,

                maxLossStreak:
                    maxLossStreak(forward),

                firstRecordIndex:
                    forward[0]?.index ??
                    null,

                lastRecordIndex:
                    forward[
                        forward.length - 1
                    ]?.index ??
                    null
            },

            forwardSuccess
        });

        cursor +=
            PRIOR_RECORDS +
            FORWARD_RECORDS;

        block++;
    }

    /*
    ---------------------------------------------------------
    STATE AGGREGATION
    ---------------------------------------------------------
    */

    const STATES = [
        "HEALTHY",
        "STABLE",
        "DECAYING",
        "BROKEN"
    ];

    function aggregateState(state) {

        const rows =
            transitions.filter(
                x =>
                    x.healthState ===
                    state
            );

        const successful =
            rows.filter(
                x =>
                    x.forwardSuccess
            ).length;

        const forwardTrades =
            rows.reduce(
                (sum, x) =>
                    sum +
                    x.forward.trades,
                0
            );

        const forwardDecisive =
            rows.reduce(
                (sum, x) =>
                    sum +
                    x.forward.decisiveTrades,
                0
            );

        const forwardNetR =
            rows.reduce(
                (sum, x) =>
                    sum +
                    x.forward.netR,
                0
            );

        const forwardWins =
            rows.reduce(
                (sum, x) =>
                    sum +
                    x.forward.wins,
                0
            );

        const forwardLosses =
            rows.reduce(
                (sum, x) =>
                    sum +
                    x.forward.losses,
                0
            );

        return {

            state,

            observations:
                rows.length,

            successfulBlocks:
                successful,

            failedBlocks:
                rows.length -
                successful,

            blockSuccessRatePct:
                rows.length
                    ? round(
                        successful /
                        rows.length *
                        100,
                        2
                    )
                    : 0,

            forwardTrades,

            forwardDecisiveTrades:
                forwardDecisive,

            forwardWins,

            forwardLosses,

            forwardNetR:
                round(
                    forwardNetR
                ),

            forwardEV:
                forwardTrades
                    ? round(
                        forwardNetR /
                        forwardTrades
                    )
                    : 0,

            forwardWinRatePct:
                forwardDecisive
                    ? round(
                        forwardWins /
                        forwardDecisive *
                        100,
                        2
                    )
                    : 0,

            meetsSuggestedSample:
                rows.length >=
                MIN_STATE_OBSERVATIONS
        };
    }

    const stateResults =
        STATES.map(
            aggregateState
        );

    /*
    ---------------------------------------------------------
    PRIMARY CONFIRMATION COMPARISON
    ---------------------------------------------------------
    */

    const healthy =
        stateResults.find(
            x =>
                x.state ===
                "HEALTHY"
        );

    const decaying =
        stateResults.find(
            x =>
                x.state ===
                "DECAYING"
        );

    const broken =
        stateResults.find(
            x =>
                x.state ===
                "BROKEN"
        );

    const stable =
        stateResults.find(
            x =>
                x.state ===
                "STABLE"
        );

    const healthyEV =
        healthy?.forwardEV ?? null;

    const decayingEV =
        decaying?.forwardEV ?? null;

    const brokenEV =
        broken?.forwardEV ?? null;

    /*
    V24 does NOT tune a threshold.

    It simply reports whether the frozen V23 hypothesis
    survives the independent block test.
    */

    const healthyObserved =
        (healthy?.observations ?? 0) >=
        MIN_STATE_OBSERVATIONS;

    const decayingObserved =
        (decaying?.observations ?? 0) >=
        MIN_STATE_OBSERVATIONS;

    const healthyBeatsDecaying =
        healthyObserved &&
        decayingObserved &&
        healthyEV > decayingEV;

    const healthyPositive =
        healthyObserved &&
        healthyEV > 0;

    let confirmationClassification =
        "INCONCLUSIVE";

    if (
        healthyObserved &&
        decayingObserved
    ) {

        if (
            healthyPositive &&
            healthyBeatsDecaying
        ) {
            confirmationClassification =
                "HEALTH_PERSISTENCE_SUPPORTED";
        } else if (
            !healthyPositive
        ) {
            confirmationClassification =
                "HEALTH_PERSISTENCE_REJECTED";
        } else {
            confirmationClassification =
                "HEALTH_RELATIONSHIP_NOT_REPLICATED";
        }
    }

    /*
    BROKEN IS NEVER used as a positive comparator.

    V23 showed BROKEN was unexpectedly positive with a tiny
    sample. V24 therefore reports it but deliberately does
    not optimize around it.
    */

    const brokenInterpretation =
        (broken?.observations ?? 0) <
        MIN_STATE_OBSERVATIONS
            ? "UNDERPOWERED_SAMPLE"
            : brokenEV > 0
                ? "POSITIVE_BUT_NOT_A_PROMOTION_SIGNAL"
                : "NOT_POSITIVE";

    const totalForwardTrades =
        transitions.reduce(
            (sum, x) =>
                sum +
                x.forward.trades,
            0
        );

    const totalForwardNetR =
        transitions.reduce(
            (sum, x) =>
                sum +
                x.forward.netR,
            0
        );

    return {

        success:
            true,

        version:
            VERSION,

        status:
            "COMPLETED",

        mode:
            "V24_INDEPENDENT_EDGE_HEALTH_CONFIRMATION",

        paperOnly:
            true,

        realOrders:
            false,

        brokerOrderEnabled:
            false,

        brokerOrderSent:
            false,

        purpose:
            "Independently confirm whether the frozen V22.8/V22.9 edge-health states carry forward-persistence information on a non-overlapping chronological confirmation slice.",

        hypothesis:
            "HEALTHY should outperform DECAYING on an independent chronological sample if the V23 relationship is genuine.",

        source: {

            label:
                sourceLabel,

            independentFromV23:
                sourceLabel ===
                "SEPARATE_HISTORICAL_SLICE",

            startTs:
                sourceStartTs,

            endTs:
                sourceEndTs,

            records:
                records.length,

            sellRecords:
                records.length
        },

        frozenDefinitions: {

            HEALTHY:
                "prior EV > 0 AND internal EV change >= -0.10R AND late-half EV > 0",

            STABLE:
                "prior EV > 0 AND internal EV change >= -0.10R AND late-half EV <= 0",

            DECAYING:
                "prior EV > 0 AND internal EV change < -0.10R AND late-half EV > 0",

            BROKEN:
                "prior EV > 0 AND internal EV change < -0.10R AND late-half EV <= 0",

            internalEVDecayThreshold:
                HEALTH_DECAY_THRESHOLD
        },

        geometry: {

            priorRecords:
                PRIOR_RECORDS,

            forwardRecords:
                FORWARD_RECORDS,

            overlappingBlocks:
                false,

            independentBlocks:
                true,

            blockStep:
                PRIOR_RECORDS +
                FORWARD_RECORDS
        },

        sample: {

            usableSELLRecords:
                records.length,

            independentBlocks:
                transitions.length,

            totalForwardTrades,

            totalForwardNetR:
                round(
                    totalForwardNetR
                ),

            minimumStateObservations:
                MIN_STATE_OBSERVATIONS
        },

        stateResults,

        primaryConfirmation: {

            healthyObserved,

            decayingObserved,

            healthyForwardEV:
                healthyEV,

            decayingForwardEV:
                decayingEV,

            healthyMinusDecayingEV:
                healthyEV !== null &&
                decayingEV !== null
                    ? round(
                        healthyEV -
                        decayingEV
                    )
                    : null,

            healthyPositive,

            healthyBeatsDecaying,

            classification:
                confirmationClassification
        },

        brokenDiagnostic: {

            observations:
                broken?.observations ??
                0,

            forwardEV:
                brokenEV,

            interpretation:
                brokenInterpretation,

            usedForPromotion:
                false
        },

        stableDiagnostic: {

            observations:
                stable?.observations ??
                0,

            forwardEV:
                stable?.forwardEV ??
                null,

            usedForPromotion:
                false
        },

        blockResults:
            transitions,

        antiLeakage: {

            chronological:
                true,

            nonOverlappingConfirmationBlocks:
                true,

            priorWindowOnly:
                true,

            forwardWindowUsedOnlyForOutcome:
                true,

            futureOutcomeUsedForHealthState:
                false,

            futureOutcomeUsedForStateSelection:
                false,

            thresholdTuningFromConfirmation:
                false,

            v23OutcomeUsedToModifyV24Threshold:
                false,

            productionPipelineModified:
                false,

            candidateDiscoveryModified:
                false,

            validationModified:
                false,

            oosModified:
                false,

            exitModelModified:
                false,

            riskModified:
                false
        },

        decisionGuard: {

            noTradingChange:
                true,

            noThresholdTuning:
                true,

            noStatePromotion:
                true,

            noAutomaticFilter:
                true,

            noLiveTrading:
                true,

            interpretation:
                "V24 is a replication test only. Even a positive result does not create a trading rule. Any later strategy integration requires another explicitly declared chronological test."
        },

        interpretationGuard:
            "V24 must not be interpreted as proof of live profitability. It tests whether the V23 edge-health relationship replicates on non-overlapping chronological observations."
    };
}

/*
===========================================================
 INTEGRATION NOTE
 ----------------------------------------------------------

 Keep the existing V23 trading engine and all strategy
 mechanics unchanged.

 V24 should receive LEARNING RECORDS produced by those
 unchanged mechanics from a SEPARATE historical period.

 Recommended flow:

   EXISTING ENGINE
        |
        | separate historical slice
        v
   learningRecords
        |
        v
   buildV240IndependentEdgeHealthConfirmation(...)
        |
        v
   JSON ONLY

 DO NOT:
   - feed V24 confirmation outcomes back into discovery
   - change HEALTHY/DECAYING/BROKEN definitions
   - select a threshold after seeing V24 results
   - add HEALTHY as a live filter
   - remove DECAYING/BROKEN from trading
   - alter validation/OOS
   - alter exits/risk

 ===========================================================
*/
